# Build stage
ARG PYTHON_VERSION=3.8
FROM python:${PYTHON_VERSION} as base
WORKDIR /app

COPY . ./

FROM python:${PYTHON_VERSION}-slim
WORKDIR /app

COPY --from=base /app .

RUN pip install --upgrade pip && \
pip install -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]